# run with: docker-compose -f docker-compose.no-localhost.yml up -d
# use docker network inspect jne_network to get the IP addresses of the containers

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: deglanrivas/prueba_jne_productos_frontend:1.9.0
    container_name: saas_frontend
    environment:
      - VITE_BACKEND_URL=http://172.19.0.3:8000
    depends_on:
      - backend
    networks:
      - jne_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: deglanrivas/prueba_jne_productos_backend:1.0.0
    container_name: saas_backend
    environment:
      - MONGO_URI=mongodb://mongodb_jne:27017
      - FRONTEND_URL=http://172.19.0.4
    depends_on:
      - mongodb_jne
    networks:
      - jne_network

  mongodb_jne:
    image: mongo:8
    container_name: mongodb_jne
    volumes:
      - mongo_data_jne:/data/db
    networks:
      - jne_network

volumes:
  mongo_data_jne:

networks:
  jne_network:
    driver: bridge