# version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.single-stage
    image: deglanrivas/prueba_jne_productos_frontend:dev
    container_name: saas_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=/api
    depends_on:
      - backend
    networks:
      - jne_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: deglanrivas/prueba_jne_productos_backend:1.1.0
    container_name: saas_backend
    environment:
      - MONGO_URI=mongodb://mongodb_jne:27017
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb_jne
    networks:
      - jne_network

  mongodb_jne:
    image: mongo:8
    container_name: mongodb_jne
    volumes:
      - mongo_data_jne:/data/db
    networks:
      - jne_network

volumes:
  mongo_data_jne:

networks:
  jne_network:
    driver: bridge